dataapp/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'dataapp'

urlpatterns = [
   url(r'^$', views.index, name='index'),
   url(r'^json/',views.list,name='json'),
   url(r'^json2/',views.ItemApi,name='item')
]

learnIt/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path
from dataapp import views
from learnIt import settings

urlpatterns = [
   url(r'^$',views.index,name='home'),
   url(r'^dataapp/',include('dataapp.urls')),
  path('admin/', admin.site.urls),
    
]

dataapp/models.py
from django.db import models

# Create your models here.
from django.db import models


class SensorHtp(models.Model):
    sno = models.IntegerField(db_column='SNO', unique=True, blank=True, null=True)  # Field name made lowercase.
    timestamp = models.CharField(db_column='TimeStamp', max_length=25, blank=True, null=True)  # Field name made lowercase.
    nodeid = models.IntegerField(db_column='NODEID')  # Field name made lowercase.
    humidity = models.IntegerField(db_column='Humidity', blank=True, null=True)  # Field name made lowercase.
    temp = models.IntegerField(db_column='TEMP', blank=True, null=True)  # Field name made lowercase.
    pressure = models.IntegerField(db_column='Pressure', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Sensor_HTP'


class SensorTl(models.Model):

    sno = models.IntegerField(db_column='SNO', primary_key=True, blank=False, null=False)  # Field name made lowercase.
    timestamp = models.CharField(db_column='TimeStamp', max_length=25, blank=True, null=True)  # Field name made lowercase.
    nodeid = models.IntegerField(db_column='NODEID')  # Field name made lowercase.
    light = models.TextField(db_column='LIGHT', blank=True, null=True)  # Field name made lowercase. This field type is a guess.
    temp = models.TextField(db_column='TEMP', blank=True, null=True)  # Field name made lowercase. This field type is a guess.

    class Meta:
        managed = False
        db_table = 'Sensor_TL'


class Asdf(models.Model):
    sno = models.IntegerField(db_column='SNO', unique=True, blank=True, null=True)  # Field name made lowercase.
    timestamp = models.CharField(db_column='TimeStamp', max_length=25, blank=True, null=True)  # Field name made lowercase.
    nodeid = models.IntegerField(db_column='NODEID')  # Field name made lowercase.
    light = models.IntegerField(blank=True, null=True)
    temp = models.IntegerField(blank=True, null=True)
    time = models.TextField(blank=True, null=True)  # This field type is a guess.

    class Meta:
        managed = False
        db_table = 'asdf'

dataapp/views.py
from django.http import HttpResponse
from django.http import JsonResponse
from dataapp.models import SensorTl
from django.shortcuts import render
from django.core import serializers


def index(request):
    return render(request,'getTable.html')
 	


def ItemApi(request):
	
	SensorData = SensorTl.objects.all()
	
	List = []

	for obj in SensorData:
		tempData={
		"Time_Stamp" : obj.timestamp,
		"Node_Id": obj.nodeid,
		"light":obj.light,
		"temp":obj.temp,
		
		}
		List.append(tempData)
		

	data = {}
	data['success']=True
	data['item'] = List

	return JsonResponse(data,safe=False)	

def list(request):
	queryset= SensorTl.objects.all()
	queryset = serializers.serialize('json',queryset)
	return HttpResponse(queryset,content_type="json")

templates/getTable.html
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width initial-scale=1">
	
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <title>Table Search</title>
</head>
<body>
	<div class="container" align="center">
		<h1 >Sensor Tl Data </h1>
		
		<button type="button" class ="btn-success" id="btn">Retrieve Data</button>
		<br>
		<input type="text" class="search" id="myInput" onkeyup="searchFunction()" placeholder="type here to search"><br><br>
		<table class="table table-bordered table-striped" align="center" id="info">
		<th>Time Stamp</th><th>Node Id</th><th>Light</th><th>Temp</th>
		</table><br>
		<center><h4 >Total no. of records : </h4><h3 id="count"></h3></center>
	</div>

	<script type="text/javascript">
		var info = document.getElementById('info');
var btn = document.getElementById('btn');
document.getElementById('count').innerHTML=0;
document.getElementById('myInput').style.display='none';
btn.addEventListener('click',function() {

});
var i=0;


var htmlString = "";

function renderHTML(data){
	

	for(i=0;i<data.length;i++){
		htmlString += "<tr><td>" + data[i].fields.timestamp + "</td><td>" + data[i].fields.nodeid + "</td><td>" +data[i].fields.light +"</td><td>" +data[i].fields.temp+"</td></tr>";
	}
	if(i==data.length)
	{
		document.getElementById('count').innerHTML=i;
		document.getElementById('btn').innerHTML='Refresh';
		document.getElementById('myInput').style.display='inline';

	}
	info.innerHTML="";

	info.insertAdjacentHTML('beforeend' , htmlString);
}
setInterval(function(){

	
	// $( "info" ).remove();
	var xhttp = new XMLHttpRequest();

	xhttp.open('GET',"{% url 'dataapp:json' %}");
	xhttp.onload = function(){
		var data = JSON.parse(xhttp.responseText);
		console.log(data);
		renderHTML(data);
	};
	xhttp.send();
},10000);


function searchFunction() {
  // Declare variables 
  var input, filter, table, tr, td,td1,td2,td3, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("info");
  tr = table.getElementsByTagName("tr");
  var count=0;


  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
   
    td1 = tr[i].getElementsByTagName("td")[0];
    td2 = tr[i].getElementsByTagName("td")[1];
    td3 = tr[i].getElementsByTagName("td")[2];
    td = tr[i].getElementsByTagName("td")[3]
    
      if(td+td2+td3+td1){
			if((td.innerHTML.toUpperCase().indexOf(filter)+td2.innerHTML.toUpperCase().indexOf(filter)+
				td3.innerHTML.toUpperCase().indexOf(filter)+td1.innerHTML.toUpperCase().indexOf(filter))>-4)
			{
				tr[i].style.display = "";
				count++;
				
			}
			else{
				tr[i].style.display = 'none';

			}  
		}
    
  }
  document.getElementById('count').innerHTML=count;

}
	</script>

</body>
</html>